### ISSUE TITLE
Caused by: java.io.IOException: Authorization loop detected on Conduit

### ISSUE THREAD

**Issue by techdinesh** [cloudsoft/winrm4j#117]
I tried a simple WinRM client example using the code as follows, and unable to execute the command successfully due to the below exception.

Here is the code below snippet while connecting to client-server, Any idea what could be wrong in this simple code. Thanks
`public static void main(String [] args) {
	WinRmClientContext context = WinRmClientContext.newInstance();
	
	WinRmTool.Builder builder = WinRmTool.Builder.builder("192.168...**.**", "username", "password");
    builder.disableCertificateChecks(true);
    builder.setAuthenticationScheme(AuthSchemes.NTLM);
    builder.port(WinRmTool.DEFAULT_WINRM_HTTPS_PORT);
    builder.useHttps(true);
    WinRmTool tool = builder.build();
    WinRmToolResponse result = tool.executeCommand("echo hello")
    context.shutdown();
}`

Here is the exception message :
-----------------------------------
`

java.lang.RuntimeException: failed task create
	at io.cloudsoft.winrm4j.client.RetryingProxyHandler.invokeWithRetry(RetryingProxyHandler.java:67)
	at io.cloudsoft.winrm4j.client.RetryingProxyHandler.invoke(RetryingProxyHandler.java:34)
	at com.sun.proxy.$Proxy2310.create(Unknown Source)
	at io.cloudsoft.winrm4j.client.WinRmClient.createShell(WinRmClient.java:344)
	at io.cloudsoft.winrm4j.winrm.WinRmTool.executeCommand(WinRmTool.java:282)
	at io.cloudsoft.winrm4j.winrm.WinRmTool.executePs(WinRmTool.java:298)
	at com.paychex.eba.totem.scripts.TakeXLReleaseHeapDump$Execute.callHeapDump(TakeXLReleaseHeapDump.xtend:215)
	at com.paychex.eba.totem.scripts.TakeXLReleaseHeapDump$Execute.executeCommand(TakeXLReleaseHeapDump.xtend:125)
	at com.paychex.eba.totem.scripts.TakeXLReleaseHeapDump$Execute.execute(TakeXLReleaseHeapDump.xtend:96)

Caused by: javax.xml.ws.WebServiceException: Could not send Message.
	at org.apache.cxf.jaxws.JaxWsClientProxy.mapException(JaxWsClientProxy.java:183)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:145)
	at com.sun.proxy.$Proxy2309.create(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.cloudsoft.winrm4j.client.RetryingProxyHandler.invokeWithRetry(RetryingProxyHandler.java:44)
	... 58 more
Caused by: java.io.IOException: Authorization loop detected on Conduit "{http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd}WinRmPort.http-conduit" on URL "http://severname:5985/wsman" with realm "WSMAN"
	at org.apache.cxf.transport.http.HTTPConduit.detectAuthorizationLoop(HTTPConduit.java:1948)
	at org.apache.cxf.transport.http.HTTPConduit.access$600(HTTPConduit.java:150)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.authorizationRetransmit(HTTPConduit.java:1528)
	at org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduit$AsyncWrappedOutputStream.authorizationRetransmit(AsyncHTTPConduit.java:807)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.processRetransmit(HTTPConduit.java:1463)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleRetransmits(HTTPConduit.java:1437)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1567)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1373)
	at org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduit$AsyncWrappedOutputStream.close(AsyncHTTPConduit.java:417)
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:673)
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:63)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:531)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:440)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:355)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:313)
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:140)
	... 64 more

`
Hi, [@nbahramzad](https://github.com/nbahramzad), As per your suggestion please elaborate a little more on this issue, so that we can resolve this ticket as well.

**Comment by aledsage** [comment]
@techdinesh this sounds very similar to the following:
* https://github.com/cloudsoft/winrm4j/issues/73
* https://stackoverflow.com/questions/46299280/winrm4j-authorization-loop-detected-on-conduit-on-url-with-realm-null

Quoting @neykov 's response from https://github.com/cloudsoft/winrm4j/issues/73#issuecomment-330481447:

It means that authentication failed - either your credentials are not valid or the server is misconfigured. There's an open issue on this - https://github.com/cloudsoft/winrm4j/issues/55.
See some tips for troubleshooting this https://docs.cloudsoft.io/blueprints/base-blueprints/winrm/client.html#winrm-connectivity-diagnostics
