### ISSUE TITLE
"Could not send Message" exception when running the code sample from the readme.

### ISSUE THREAD

**Issue by dvucko** [cloudsoft/winrm4j#46]
I'm trying to use winrm4j 0.3.2 on Linux Mint 17.2 using Java 8 (openjdk 1.8), but can't get it to work. Code:

```
WinRmTool.Builder builder = WinRmTool.Builder.builder("myserver.domain.org", "localhost\\Administrator", "pwd");
builder.setAuthenticationScheme(AuthSchemes.NTLM);
builder.port(WinRmTool.DEFAULT_WINRM_PORT);
builder.useHttps(false);
WinRmTool tool =  builder.build();
WinRmToolResponse response = tool.executePs("hostname");
System.out.println(response.getStdOut());
```
This fails with the "javax.xml.ws.WebServiceException: Could not send Message." exception.  What am I doing wrong?

Note that the target host is configured correctly and I can perform the above WinRM operation on it normally using other librarires and tools (WinRb, PowerShell ...), using either Negotiate or Kerberos - it's only winrm4j that doesn't appear to work.

Stack trace/output:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Jan 05, 2017 1:37:18 PM org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean buildServiceFromWSDL
INFO: Creating Service {http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd}WinRmService from WSDL: ...
Jan 05, 2017 1:37:21 PM org.apache.cxf.transport.http.HTTPConduit detectAuthorizationLoop
INFO: Authorization loop detected on Conduit "{http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd}WinRmPort.http-conduit" on URL "http://myserver.domain.org:5985/wsman" with realm "null"
Jan 05, 2017 1:37:21 PM org.apache.cxf.phase.PhaseInterceptorChain doDefaultLogging
WARNING: Interceptor for {http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd}WinRmService#{http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd}Create has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Could not send Message.
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:64)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:514)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:423)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:324)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:277)
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:139)
	at com.sun.proxy.$Proxy45.create(Unknown Source)
	at io.cloudsoft.winrm4j.client.WinRmClient.createService(WinRmClient.java:457)
	at io.cloudsoft.winrm4j.client.WinRmClient.getService(WinRmClient.java:340)
	at io.cloudsoft.winrm4j.client.WinRmClient.command(WinRmClient.java:207)
	at io.cloudsoft.winrm4j.winrm.WinRmTool.executeCommand(WinRmTool.java:198)
	at io.cloudsoft.winrm4j.winrm.WinRmTool.executePs(WinRmTool.java:213)
	at Main.main(Main.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.io.IOException: Authorization loop detected on Conduit "{http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd}WinRmPort.http-conduit" on URL "http://myserver.domain.org:5985/wsman" with realm "null"
	at org.apache.cxf.transport.http.HTTPConduit.detectAuthorizationLoop(HTTPConduit.java:1926)
	at org.apache.cxf.transport.http.HTTPConduit.access$600(HTTPConduit.java:147)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.authorizationRetransmit(HTTPConduit.java:1506)
	at org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduit$AsyncWrappedOutputStream.authorizationRetransmit(AsyncHTTPConduit.java:796)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.processRetransmit(HTTPConduit.java:1437)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleRetransmits(HTTPConduit.java:1411)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1545)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1347)
	at org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduit$AsyncWrappedOutputStream.close(AsyncHTTPConduit.java:415)
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:651)
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62)
	... 19 more

Exception in thread "main" javax.xml.ws.WebServiceException: Could not send Message.
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:150)
	at com.sun.proxy.$Proxy45.create(Unknown Source)
	at io.cloudsoft.winrm4j.client.WinRmClient.createService(WinRmClient.java:457)
	at io.cloudsoft.winrm4j.client.WinRmClient.getService(WinRmClient.java:340)
	at io.cloudsoft.winrm4j.client.WinRmClient.command(WinRmClient.java:207)
	at io.cloudsoft.winrm4j.winrm.WinRmTool.executeCommand(WinRmTool.java:198)
	at io.cloudsoft.winrm4j.winrm.WinRmTool.executePs(WinRmTool.java:213)
	at Main.main(Main.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.io.IOException: Authorization loop detected on Conduit "{http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd}WinRmPort.http-conduit" on URL "http://myserver.domain.org:5985/wsman" with realm "null"
	at org.apache.cxf.transport.http.HTTPConduit.detectAuthorizationLoop(HTTPConduit.java:1926)
	at org.apache.cxf.transport.http.HTTPConduit.access$600(HTTPConduit.java:147)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.authorizationRetransmit(HTTPConduit.java:1506)
	at org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduit$AsyncWrappedOutputStream.authorizationRetransmit(AsyncHTTPConduit.java:796)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.processRetransmit(HTTPConduit.java:1437)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleRetransmits(HTTPConduit.java:1411)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1545)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1347)
	at org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduit$AsyncWrappedOutputStream.close(AsyncHTTPConduit.java:415)
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:651)
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:514)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:423)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:324)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:277)
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:139)
	... 12 more

```

**Comment by neykov** [comment]
The errors means that it can't authenticate correctly.
Try removing the "localhost\" prefix from the user name.

**Comment by dvucko** [comment]
@neykov removing 'localhost' doesn't change anything. The credentials are 100% correct - I get the same problem with different hosts, all of which can be accessed normally via WinRM.

**Comment by neykov** [comment]
Try the following steps: http://docs.cloudsoft.io/blueprints/base-blueprints/winrm/client.html#winrm-connectivity-diagnostics
They assume [Brooklyn](https://brooklyn.apache.org) but work for plain winrm4j as well.

If that doesn't work out paste the output of the commands here.

**Comment by neykov** [comment]
Also try latest released version - 4.0.0, we really need to update the README.

**Comment by dvucko** [comment]
Thank you. The problem was that I had to manually set AllowUnencrypted="true" on the host - something I didn't have to do when I used other libs and APIs. Is there an example of how I can correctly get winrm4j working with HTTPS? I tried the following code, but get a "org.apache.cxf.interceptor.Fault: Could not send Message" exception.
```

builder.port(WinRmTool.DEFAULT_WINRM_HTTPS_PORT);
builder.useHttps(true);
builder.disableCertificateChecks(true);

```

**Comment by neykov** [comment]
What's the full stack trace?

**Comment by dvucko** [comment]
@neykov I updated the previous post with the stack trace.

**Comment by neykov** [comment]
It means the `http` port is not open. It's firewalled or not enabled at all. See [this KB](https://support.microsoft.com/en-us/kb/2019527) for enabling `https`.
The windows tools are able to talk on the `http` port and do application-level encryption. That's why they don't need `AllowUnencrypted`.

**Comment by neykov** [comment]
Btw here's a script that will configure https for you:
https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1

**Comment by dvucko** [comment]
@neykov thank you. Do you know if it's possible to configure winrm/https remotely? I would really like to avoid having to manually connect to each host in order to configure it. Moreover, is it even possible to implement/modify the code in a way that would make it consistent with MS's implementation, so that AllowUnencrypted=true wouldn't be needed in case I want to use http? The way things are now on Linux kind of defeats the purpose of WinRM for me, as I have to configure each host to be managed manually.

**Comment by neykov** [comment]
In your case (allowUnencrypted=false & only http port is open) it's not possible to connect with winrm4j and update the remote machine. It is certainly possible to improve the implementation to support application-level encryption but this is not something that is currently being worked on.

In the context of Apache Brooklyn, which is the reason this library got created, we can work around the limitation by asking the cloud provider to give us a properly configured machine.
