### ISSUE TITLE
Add support for encryption over http

### ISSUE THREAD

**Issue by neykov** [cloudsoft/winrm4j#70]
The protocol `winrm4j` implements supports application-level encryption which will encrypt the body of the requests even when running through plain `http` protocol. The advantage over using the `https` protocol is easier initial setup. Newly provisioned machines are configured to require encryption, which could either be application level through `http` or at the protocol layer with `https`. Using `https` though requires setting up of a certificate on the remote machine, usually self-signed (resulting in trust-all config) which is harder to set up and not more secure.

**Comment by andreaturli** [comment]
If I get this correctly this will allow `winrm4j` to work with configurations like
```
 MaxConcurrentOperations = 4294967295
 MaxConcurrentOperationsPerUser = 1500
 EnumerationTimeoutms = 240000
 MaxConnections = 300
 MaxPacketRetrievalTimeSeconds = 120
 AllowUnencrypted = false
 Auth
     Basic = false
     Kerberos = true
     Negotiate = true
     Certificate = false
     CredSSP = true
     CbtHardeningLevel = Relaxed
 DefaultPorts
     HTTP = 5985
     HTTPS = 5986
 IPv4Filter = *
 IPv6Filter = *
 EnableCompatibilityHttpListener = false
 EnableCompatibilityHttpsListener = false
 CertificateThumbprint
 AllowRemoteAccess = true
```
where `AllowUnencrypted = false` is the interesting bit

Notice this is extracted from a recent AWS Windows_Server-2012-R2_RTM-English-64Bit-Base AMI so looks particularly common.

@neykov How would it be required to support that?

**Comment by neykov** [comment]
That's right, it will allow winrm4j to work with default image configurations, but most importantly removes the need for generating server certificates which is a pain.
I believe it's not a particularly hard thing to implement, the challenge would be to integrate it with CXF (a layer between jax-rs and the http library?)
Here's how the ruby implementation [has done it](https://github.com/WinRb/WinRM/blob/18f934ef05e43b8e630f43c74edb29c20c131c1c/lib/winrm/http/transport.rb#L166-L188). They generate the encrypted message "by hand", concatenating a bunch of strings - something that the apache http client [can already handle](https://stackoverflow.com/a/2981395).

**Comment by charlesm-chtr** [comment]
I have an implementation where "allowUnencrypted=false" is the norm. It seems that the library supports HTTP-SPNEGO-session-encrypted in:
client/src/main/java/io/cloudsoft/winrm4j/client/WinRmClient.java
client/src/main/java/io/cloudsoft/winrm4j/client/ntlm/SpNegoNTLMSchemeFactory.java
client/src/main/java/io/cloudsoft/winrm4j/client/ntlm/ApacheSpnegoScheme.java

However, when I set the builder.authenticationScheme("SPNEGO"); and it returns "No such authentication scheme SPNEGO".

**Comment by poorna2k6** [comment]
Is this feature already integrated into this project ? I'm unable to do HTTP protocol request. Getting following error , can some one pleas help.

2021-05-28 11:37:11.606  INFO 22354 --- [           main] o.apache.cxf.transport.http.HTTPConduit  : Authorization loop detected on Conduit "{http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd}WinRmPort.http-conduit" on URL "http://192.168.0.48:5985/wsman" with realm "null"
2021-05-28 11:37:11.638  WARN 22354 --- [           main] o.a.cxf.phase.PhaseInterceptorChain      : Interceptor for {http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd}WinRmService#{http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd}Create has thrown exception, unwinding now

org.apache.cxf.interceptor.Fault: Could not send Message.
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:64) ~[cxf-core-3.1.4.jar:3.1.4]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) ~[cxf-core-3.1.4.jar:3.1.4]
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:514) [cxf-core-3.1.4.jar:3.1.4]
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:423) [cxf-core-3.1.4.jar:3.1.4]
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:324) [cxf-core-3.1.4.jar:3.1.4]
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:277) [cxf-core-3.1.4.jar:3.1.4]
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96) [cxf-rt-frontend-simple-3.1.4.jar:3.1.4]
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:139) [cxf-rt-frontend-jaxws-3.1.4.jar:3.1.4]
	at com.sun.proxy.$Proxy84.create(Unknown Source) [na:na]
	at io.cloudsoft.winrm4j.client.WinRmClient.createService(WinRmClient.java:407) [winrm4j-client-0.3.0.jar:na]
	at io.cloudsoft.winrm4j.client.WinRmClient.getService(WinRmClient.java:290) [winrm4j-client-0.3.0.jar:na]
	at io.cloudsoft.winrm4j.client.WinRmClient.command(WinRmClient.java:194) [winrm4j-client-0.3.0.jar:na]
	at io.cloudsoft.winrm4j.winrm.WinRmTool.executeCommand(WinRmTool.java:197) [winrm4j-0.3.0.jar:na]
	at io.cloudsoft.winrm4j.winrm.WinRmTool.executePs(WinRmTool.java:210) [winrm4j-0.3.0.jar:na]
	at com.overthere.Sample.SampleOverthereApplication.winrm4j2(SampleOverthereApplication.java:50) [classes/:na]
	at com.overthere.Sample.SampleOverthereApplication.main(SampleOverthereApplication.java:27) [classes/:na]
Caused by: java.io.IOException: Authorization loop detected on Conduit "{http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd}WinRmPort.http-conduit" on URL "http://192.168.0.48:5985/wsman" with realm "null"
	at org.apache.cxf.transport.http.HTTPConduit.detectAuthorizationLoop(HTTPConduit.java:1926) ~[cxf-rt-transports-http-3.1.4.jar:3.1.4]
	at org.apache.cxf.transport.http.HTTPConduit.access$600(HTTPConduit.java:147) ~[cxf-rt-transports-http-3.1.4.jar:3.1.4]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.authorizationRetransmit(HTTPConduit.java:1506) ~[cxf-rt-transports-http-3.1.4.jar:3.1.4]
	at org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduit$AsyncWrappedOutputStream.authorizationRetransmit(AsyncHTTPConduit.java:796) ~[cxf-rt-transports-http-hc-3.1.4.jar:3.1.4]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.processRetransmit(HTTPConduit.java:1437) ~[cxf-rt-transports-http-3.1.4.jar:3.1.4]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleRetransmits(HTTPConduit.java:1411) ~[cxf-rt-transports-http-3.1.4.jar:3.1.4]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1545) ~[cxf-rt-transports-http-3.1.4.jar:3.1.4]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1347) ~[cxf-rt-transports-http-3.1.4.jar:3.1.4]
	at org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduit$AsyncWrappedOutputStream.close(AsyncHTTPConduit.java:415) ~[cxf-rt-transports-http-hc-3.1.4.jar:3.1.4]
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56) ~[cxf-core-3.1.4.jar:3.1.4]
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:651) ~[cxf-rt-transports-http-3.1.4.jar:3.1.4]
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62) ~[cxf-core-3.1.4.jar:3.1.4]
	... 15 common frames omitted

javax.xml.ws.WebServiceException: Could not send Message.
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:150)
	at com.sun.proxy.$Proxy84.create(Unknown Source)
	at io.cloudsoft.winrm4j.client.WinRmClient.createService(WinRmClient.java:407)
	at io.cloudsoft.winrm4j.client.WinRmClient.getService(WinRmClient.java:290)
	at io.cloudsoft.winrm4j.client.WinRmClient.command(WinRmClient.java:194)
	at io.cloudsoft.winrm4j.winrm.WinRmTool.executeCommand(WinRmTool.java:197)
	at io.cloudsoft.winrm4j.winrm.WinRmTool.executePs(WinRmTool.java:210)
	at com.overthere.Sample.SampleOverthereApplication.winrm4j2(SampleOverthereApplication.java:50)
	at com.overthere.Sample.SampleOverthereApplication.main(SampleOverthereApplication.java:27)
Caused by: java.io.IOException: Authorization loop detected on Conduit "{http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd}WinRmPort.http-conduit" on URL "http://192.168.0.48:5985/wsman" with realm "null"
	at org.apache.cxf.transport.http.HTTPConduit.detectAuthorizationLoop(HTTPConduit.java:1926)
	at org.apache.cxf.transport.http.HTTPConduit.access$600(HTTPConduit.java:147)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.authorizationRetransmit(HTTPConduit.java:1506)
	at org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduit$AsyncWrappedOutputStream.authorizationRetransmit(AsyncHTTPConduit.java:796)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.processRetransmit(HTTPConduit.java:1437)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleRetransmits(HTTPConduit.java:1411)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1545)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1347)
	at org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduit$AsyncWrappedOutputStream.close(AsyncHTTPConduit.java:415)
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:651)
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:514)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:423)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:324)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:277)
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:139)
	... 8 more

**Comment by ahgittin** [comment]
implemented in https://github.com/cloudsoft/winrm4j/pull/142
