### ISSUE TITLE
Jar Library does not have client or server dependencies/modules

### ISSUE THREAD

**Issue by rhtyd** [cloudsoft/winrm4j#82]
Hi,

The jar for 0.5.0 version does not include the client or server modules. I also inspected the jar to find the `client` folder missing. I was trying out the basic example where it failed for me with:

```
java.lang.NoClassDefFoundError: io/cloudsoft/winrm4j/client/WinRmClient

	at io.cloudsoft.winrm4j.winrm.WinRmTool.executeCommand(WinRmTool.java:210)
	at io.cloudsoft.winrm4j.winrm.WinRmTool.executePs(WinRmTool.java:258)
```

**Comment by rhtyd** [comment]
Found the fix, there is another win4jrm-client mvn dependency that needed to be added. Please make it explicit in docs author.
